apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: netflix-replica
  namespace: murali-ns
spec:
  replicas: 10
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: c-1
          image: muralisocial123/netflix-2025:latest
          ports:
            - containerPort: 80